//created on: Jul 3, 2020
package integracija

//list any import classes here.
import sbnz.integracija.example.facts.Member;

//declare any global variables here




rule "Discount 10%"
	agenda-group "membership-discount"
	no-loop
    when
    
        $m: Member($history: history, $membership: membership, $discount: discount) from entry-point "discount"
        Number($value: intValue >= 1) from accumulate(
        	BookRent($br:this) from $history,
        	count($br)
        ) 
    then
    	System.out.println("****VALUE: " + $value);
        modify($m){setDiscount($membership*0.1);}
        $discount = $m.getDiscount();
        modify($m){setMembership($membership-$discount);}
        System.out.println("*******DISCOUNT*********" + $m.getDiscount() + "\n*********MEMBERSHIP*********" + $m.getMembership());

end

