package sbnz.integracija.template;
import sbnz.integracija.example.facts.Member;

rule "Categorize Members_GOLD"
no-loop true
when
	$m: Member($m.getRented >= 555,
		   $m.getRented <= 6666)
then
	modify ($m){ setCathegory(Member.cathegory.GOLD)};
end

rule "Categorize Members_SILVER"
no-loop true
when
	$m: Member($m.getRented >= 333,
		   $m.getRented <= 444)
then
	modify ($m){ setCathegory(Member.cathegory.SILVER)};
end

rule "Categorize Members_BRONZE"
no-loop true
when
	$m: Member($m.getRented >= 22,
		   $m.getRented <= 222)
then
	modify ($m){ setCathegory(Member.cathegory.BRONZE)};
end

rule "Categorize Members_NA"
no-loop true
when
	$m: Member($m.getRented >= 3,
		   $m.getRented <= 34)
then
	modify ($m){ setCathegory(Member.cathegory.NA)};
end


