package sbnz.integracija.template;
import sbnz.integracija.example.facts.Member;

rule "Categorize Members_GOLD"
no-loop true
when
	$m: Member($m.getRented >= 76,
		   $m.getRented <= 98)
then
	modify ($m){ setCathegory(Member.cathegory.GOLD)};
end

rule "Categorize Members_SILVER"
no-loop true
when
	$m: Member($m.getRented >= 55,
		   $m.getRented <= 65)
then
	modify ($m){ setCathegory(Member.cathegory.SILVER)};
end

rule "Categorize Members_BRONZE"
no-loop true
when
	$m: Member($m.getRented >= 13,
		   $m.getRented <= 45)
then
	modify ($m){ setCathegory(Member.cathegory.BRONZE)};
end

rule "Categorize Members_NA"
no-loop true
when
	$m: Member($m.getRented >= 3,
		   $m.getRented <= 12)
then
	modify ($m){ setCathegory(Member.cathegory.NA)};
end


